import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  documentationSidebar: [
    {
      type: 'category',
      label: 'Documentation',
      collapsed: false,
      link: {type: 'doc', id: 'index'},
      items: [{type: 'autogenerated', dirName: '.'}],
    },
  ],
};

export default sidebars;
